#!/bin/bash
let i=0
for column1 in out/jpeg/col1-*.jpeg
do
    spacer=$(printf "%03d" $i)
    convert out/jpeg/col1-$spacer.jpeg out/jpeg/col2-$spacer.jpeg +append out/jpeg/combined-$spacer.jpeg
    let i++
done
